"""add unique to address

Revision ID: 04b638ba3ec5
Revises: 6988b415606f
Create Date: 2025-03-27 12:24:59.543279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b638ba3ec5'
down_revision: Union[str, None] = '6988b415606f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_queries_address', table_name='wallet_queries')
    op.create_index(op.f('ix_wallet_queries_address'), 'wallet_queries', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_queries_address'), table_name='wallet_queries')
    op.create_index('ix_wallet_queries_address', 'wallet_queries', ['address'], unique=False)
    # ### end Alembic commands ###
