"""initial2

Revision ID: 6988b415606f
Revises: 
Create Date: 2025-03-27 12:19:51.796609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6988b415606f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('balance', sa.DECIMAL(), nullable=False),
    sa.Column('bandwidth', sa.JSON(), nullable=False),
    sa.Column('energy', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_queries_address'), 'wallet_queries', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_queries_id'), 'wallet_queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_queries_id'), table_name='wallet_queries')
    op.drop_index(op.f('ix_wallet_queries_address'), table_name='wallet_queries')
    op.drop_table('wallet_queries')
    # ### end Alembic commands ###
