"""upgrade to decimal

Revision ID: e1ce9df9cf8e
Revises: 300d00a8e9ec
Create Date: 2025-03-26 17:25:07.589665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ce9df9cf8e'
down_revision: Union[str, None] = '300d00a8e9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_queries', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_queries', 'balance',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
